const jwt = require("jsonwebtoken");
const { OAuth2Client } = require("google-auth-library");

const jwtConfig = require("../../config/jwtConfig");
const UnsafeUser = require("../../models/UnsafeUser");
const initializeLogger = require("../../log-service");
const notifyAdmin = require("../../utility/email/notifyAdmin");

const moduleLogger = initializeLogger("controllers/user/googleAuth");

const cmapClientID =
  "739716651449-7d1e8iijue6srr9l5mi2iogp982sqoa0.apps.googleusercontent.com";

const standardCookieOptions = {
  // secure: true,
};

const jwtCookieOptions = {
  ...standardCookieOptions,
  httpOnly: true,
};

// Accepts a token generated by a successful google oauth sign-in.
// We verify token, then either
// - sign in user with associated google id
// - if no user with id, try to find user with same google email and attach id to user
module.exports = async (req, res, next) => {
  const log = moduleLogger.setReqId (req.requestId);

  const { userIDToken, originator } = req.body;

  log.info ('attempting to log in user via google oauth2', { originator });

  const client = new OAuth2Client(cmapClientID);

  let ticket;
  try {
    ticket = await client.verifyIdToken({
      idToken: userIDToken,
      audience: cmapClientID,
    });
  } catch (e) {
    log.error ('error calling google client verifyIdToken', { error: e });
    notifyAdmin ('Error using OAuth2 API', `There was an error while attempting to log in a user via google OAuth2 while calling 'verifyIdToken'. The originator of the login request was '${originator}'. The error message was: '${e.message}'`);
    return res.sendStatus(500);
  }

  // our app client ID, user unique google ID, user email, first, last
  const {
    aud,
    sub: googleID,
    email,
    // given_name: firstName,
    // family_name: lastName,
  } = ticket.payload;

  if (aud !== cmapClientID) {
    log.error("google auth token does not match cmap client id", { aud });
    notifyAdmin ('Error Verifying OAuth Response', `There was an error while attempting to log in a user via google OAuth2: the API response did not match the CMAP Google Client ID. The originator of the login request was '${originator}'.`);
    return res.sendStatus(500);
  }

  // User already has a google ID associated with their account
  // TODO unhandled failure case
  let googleIDUser;
  try {
    googleIDUser = await UnsafeUser.getUserByGoogleID(googleID);
  } catch (e) {
    log.error("error attempting to get user by google id", { error: e });
    // send admin email?
    return res.sendStatus(500);
  }

  if (googleIDUser) {
    let user = new UnsafeUser(googleIDUser);
    res.cookie("UserInfo", JSON.stringify(user.makeSafe()), {
      ...standardCookieOptions,
      expires: new Date(Date.now() + 1000 * 60 * 60 * 2),
    });
    res.cookie(
      "jwt",
      jwt.sign(googleIDUser.getJWTPayload(), jwtConfig.secret, {
        expiresIn: "2h",
      }),
      {
        ...jwtCookieOptions,
        expires: new Date(Date.now() + 1000 * 60 * 60 * 2),
      }
    );
    log.info ('successfully logged in user with google oauth', { userId: user.id });
    res.json(true);
    return next();
  } else {
    // No user with google id; so now
    // See if user has an account but has no associated google ID
    let existingUser;
    try {
      existingUser = await UnsafeUser.getUserByEmail(email);
    } catch (e) {
      log.error("error attempting to get user by google email", { error: e, email });
      return res.sendStatus(500);
    }

    if (existingUser) {
      // found user with same google email, but no google id; attempt to attach google id to user
      let user = new UnsafeUser({ ...existingUser, googleID });

      const [attachErr] = await user.attachGoogleIDToExistingUser();

      if (attachErr) {
        notifyAdmin ('Error Attaching Google Account', `There was an error while attempting to log in a user via google OAuth2: A user with the same email was identified but the operation failed. The originator of the login request was '${originator}'.`);
        return res.status(500).send ('Failed to associate google id to existing user');
      }

      let stringifiedUser;
      try {
        stringifiedUser = JSON.stringify(user.makeSafe());
      } catch (e) {
        log.error ('attempt to stringify user info failed', { userEmail: email });
        res.status (500).send ('Error logging in');
        next ('Error logging in user');
        notifyAdmin ('Error Preparing JWT', `There was an error while attempting to log in a user via google OAuth2: creating the JWT failed. The originator of the login request was '${originator}'.`);
        return;
      }

      res.cookie("UserInfo", stringifiedUser, {
        ...standardCookieOptions,
        expires: new Date(Date.now() + 1000 * 60 * 60 * 2),
      });

      res.cookie(
        "jwt",
        jwt.sign(user.getJWTPayload(), jwtConfig.secret, { expiresIn: "2h" }),
        {
          ...jwtCookieOptions,
          expires: new Date(Date.now() + 1000 * 60 * 60 * 2),
        }
      );

      res.json(true);
      return next();
    } else {
      // no existing user with email
      log.info ('no user exists with google cilent provided email', { googleEmail: email });
      res.status(401).send ('No such user');
      next ('attempt to login with google was unsuccessful because no user matched');
      if (originator === 'login form') {
        // only notify if it was not an automatic login
        notifyAdmin ('Unsuccessful Login with Google', `An attempt to log a user in via their Google Account was unsuccessful. The originator of the login request was '${originator}'. The email was '${email}'.`);
      }
      return;
    }
  }
}


  /*

  // New user
  let user = new UnsafeUser({
    googleID,
    email,
    firstName,
    lastName,
    username: email,
  });

  // TODO unhandled failure case saveAsNew can throw
  await user.saveAsNew();

  // TODO stringify can throw
  res.cookie("UserInfo", JSON.stringify(user.makeSafe()), {
    ...standardCookieOptions,
    expires: new Date(Date.now() + 1000 * 60 * 60 * 2),
  });

  res.cookie(
    "jwt",
    jwt.sign(user.getJWTPayload(), jwtConfig.secret, { expiresIn: "2h" }),
    { ...jwtCookieOptions, expires: new Date(Date.now() + 1000 * 60 * 60 * 2) }
  );

  res.json(true);

  return next();

*/
